### ISSUE TITLE
DB migration for new commits

### ISSUE THREAD

**Issue by thehesiod** [google/upvote#18]
I'm seeing many PRs that touch the DB schemas and no discussion about if the new releases support DB migration to the new schemas.  What is the DB migration strategy and is there one?

**Comment by chief8192** [comment]
Hi Alexander,
There *shouldn't* be any migration needed for these recent changes. We certainly haven't needed to perform any. The main takeaways are:

- The BigQueryRow Models have been deprecated in favor of streaming directly to BigQuery. However, unless you're generating huge numbers of these entities, the export job should be keeping the entities cleared out right up to the time you deploy a new version.

- The Exemption Model is still under heavy development, but this shouldn't be in use in the OSS release yet anyway.

- There have been lots of changes that rename modules, imports, etc. in the interest of cleaning up some tech debt, but these should have no impact on the schema itself.

**Comment by thehesiod** [comment]
ok great ty for the quick reply!  would be helpful if PRs which mention DB changes explicitly state that no migrations are necessary

**Comment by chief8192** [comment]
No problem, I'll make a point of it.
