### ISSUE TITLE
datetime bug in events.html?

### ISSUE THREAD

**Issue by thehesiod** [google/upvote#19]
so currently this page displays `item.occurredDt` from date returned by `/api/web/events/query?asAdmin=true&more=true&perPage=10`,  however this data does not contain this key, instead it seems to make more sense to use `lastBlockedDt`?  Or maybe `recordedDt?`  The other thing is it would be nice to be able to sort this column.  Also I added Search by Event Type, I think that's useful as well.

**Comment by thehesiod** [comment]
also let me know if I can help with a PR as I have these changes in our repo.

**Comment by chief8192** [comment]
Hey Alexander,
I'll make a note to look into this tomorrow. It's entirely possible that it's a bug. The admin UI has been in need of an overhaul for some time now. We're hoping that we might be able to overhaul it in the not-too-distant future (and ideally the user-facing UI as well), but it's hard to say when/if this might happen.

**Comment by chief8192** [comment]
Yeah, good catch. The occurred_dt property was removed from the Event model a while back, but the admin UI references weren't updated. I'm switching it over to last_blocked_dt, and should have a fix to GitHub later today.

**Comment by chief8192** [comment]
Fixed in https://github.com/google/upvote/commit/4e20a4dcc10a8632b4ea9e7cf7ca518f55d4dc6a
