### ISSUE TITLE
Add support for filtering hosts by primary user

### ISSUE THREAD

**Issue by thehesiod** [google/upvote#20]
Here's how I did it: https://github.com/farmersbusinessnetwork/upvote/commit/4c87e9b59d67215f7430463f68b1984f4ff13cf9

**Comment by thehesiod** [comment]
btw, another thing missing for all of these search pages is wildcard support

**Comment by chief8192** [comment]
That whole search widget is definitely less that ideal, and is something that we hope to replace if we overhaul the admin UI.

**Comment by thehesiod** [comment]
ok going to add another feature request: sorting by column :)

**Comment by thehesiod** [comment]
closing this in favor of https://github.com/google/upvote/issues/24
