### ISSUE TITLE
Event deduping leads to incorrect event results

### ISSUE THREAD

**Issue by thehesiod** [google/upvote#25]
I'm still debugging how deduping works, however what I do know is that if a machine is in monitor mode, executes something that is not allowed, an ALLOW_UNKNOWN event is recorded to the datastore.

If now you move the machine to lockdown, attempt to execute the same executable, you'll get the santa warning, and eventually the event will get synced, and the recorded and last_blocked will get updated, however the event_type will stay at ALLOW_UNKNOWN.

So if you go to the events page it will list the executable as ALLOW_UNKNOWN, when in reality it was blocked.

**Comment by msuozzo** [comment]
Just so I'm clear, you're describing the following:

1. Monitor-mode Host executes binary A and it runs
1. Event displays ALLOW_UNKNOWN
1. Move Host to Lockdown mode
1. Lockdown-mode Host executes binary A and it gets blocked
1. Event displays ALLOW_UNKNOWN  <-- should be BLOCK_UNKNOWN

I would expect [this](https://github.com/google/upvote/blob/master/upvote/gae/datastore/models/santa.py#L75) line to dedupe a later event's type to the correct one. If it's not doing so, this is a bug.

Can you confirm this behavior?

**Comment by thehesiod** [comment]
correct, I think maybe this: https://github.com/google/upvote/blob/master/upvote/gae/datastore/models/base.py#L107 is the issue?   I'm going to check in stackdriver

**Comment by msuozzo** [comment]
But isn't that what you want? In that case, the newer Event's event_type will be set, no?

**Comment by thehesiod** [comment]
no, look:

```python
  def _DedupeEarlierEvent(self, earlier_event):
    """Updates if the related Event occurred earlier than the current one."""
    self.first_blocked_dt = earlier_event.first_blocked_dt
    self.event_type = earlier_event.event_type
```
it's overriding `self.event_type` (the newer/recent event), to the earlier's (from DB) event type

**Comment by msuozzo** [comment]
Ahhh my mistake. Yeah it makes sense to just move that to the DedupeMoreRecentEvent. I'll make the change.

**Comment by msuozzo** [comment]
Oh wait yeah so the base Event and SantaEvent disagreed on how to dedupe event_type. I'll fix the base implementation and remove that behavior from the Santa version of the model.

**Comment by msuozzo** [comment]
Okay the fix is in. It'll be updated in the next export.
