### ISSUE TITLE
missing indicator of regex white/blacklisting in events listing

### ISSUE THREAD

**Issue by thehesiod** [google/upvote#30]
seems like the method should also take host, path, and somehow get the globalregex settings

**Comment by msuozzo** [comment]
A Blockable's state doesn't really relate to an event (or, for that matter, a host or a path). The Blockable is still not whitelisted even if it was permitted to run at a specific path on a specific host. This dissonance highlights the questionable security properties of path-based whitelisting: The execution path can often be manipulated by an attacker or by a curious/malicious insider and is not constant for a given binary.

That said, the current usage of the "Blockable state" doesn't always line up with what is desirable. Notably, the Blockable list page is really a listing of Events. Still, I think it might be valuable to maintain consistency in the display of the Blockable state for situation when, for example, the user runs a binary successfully, moves it, and runs it again only for it to be blocked. Telling the user that the binary is "whitelisted" is inconsistent with the actual policy.

Instead, what I might suggest would be to add a secondary UI indicator (e.g. an icon) that would convey the fact that the event's outcome was influenced by the binary path. This avoids muddling the user's understanding of policy while still providing the requisite information to explain the actions that took place.

**Comment by thehesiod** [comment]
ya I had forgotten that blockables don't have paths ;)  so ya it seems having an indicator on the events page makes a lot of sense.  I've renamed the issue accordingly.  thanks for feedback.

**Comment by thehesiod** [comment]
added in https://github.com/farmersbusinessnetwork/upvote/commit/c8b91ce50e14ed3cfba2b748effe7c210d94817f, closing in favor of https://github.com/google/upvote/issues/24
