### ISSUE TITLE
logupload endpoint missing

### ISSUE THREAD

**Issue by thehesiod** [google/upvote#41]
when we set a host to upload logs, we're getting 404 on GET [PROJ].appspot.com/api/santa/logupload/[HOSTID]

**Comment by russellhancox** [comment]
The log upload stage in Santa has been somewhat broken for some time and no-one had noticed, so we removed it from the client rather than fix it. If this is a feature you really want, please open an issue on the Santa project so we can consider re-adding (and fixing) it.

**Comment by chief8192** [comment]
Thanks for clarifying, Russell. I thought that was only the case for binary upload.

**Comment by thehesiod** [comment]
well, it's still available via the upvote UI: https://github.com/google/upvote/blob/master/upvote/gae/modules/upvote_app/frontend/admin_ui/hostpage/hosts.html#L158

**Comment by chief8192** [comment]
Yeah, that bit should have been deleted as well

**Comment by thehesiod** [comment]
k, will leave this open for that part to get removed then

**Comment by thehesiod** [comment]
don't forget https://github.com/google/upvote/blob/master/upvote/gae/modules/santa_api/sync.py#L304  and I think there are implications in the DB as well
