### ISSUE TITLE
Actively Maintained or Abandoned?

### ISSUE THREAD

**Issue by leereichardt** [google/upvote#69]
There have been no updates on this since 2019. Does anyone know if this is still supported and actively maintained as it currently won't install on Big Sur, even following others advice with using a previous version of Bazel

**Comment by mellow-hype** [comment]
+1 on this, would really like to have an idea of whether we can expect updates to this repo any time soon. Thanks!

**Comment by chief8192** [comment]
Former Upvote developer here. The internal codebase has drifted quite a bit from the open source version due to very non-trival Python3 migration issues. While I can't speak for the current team, they certainly do want to resume open source releases, but at the moment, there isn't a timeframe for when that could happen.

**Comment by kempu** [comment]
Based on the Google Blog post, it seems this project will not be updated anymore? 😕 
https://cloud.google.com/blog/topics/developers-practitioners/peer-reviewed-allow-and-deny-software-installation-decisions-enable-scalable-protection
"_While we continue to evolve this solution inside Google, we've released an example repo to help you see how we handled early implementation. **We won't be publishing further updates to the codebase**; we hope this can be helpful to other companies looking to better handle their allow/deny decisions at scale._"

**Comment by leereichardt** [comment]
I mean, I don't think that's entirely surprising though, right? Google does seem to just stop and close down products at the drop of a hat? As sad as that may be... I'd love to use this "example repo" in our org but it's outside of our expertise to develop a product. Hence the reaching out to third party systems.

**Comment by bengrooters** [comment]
Hi, I’m the manager of the team that makes Upvote and was involved in the blog post and the ongoing decision not to make releases to this repository.
I hear what you’re saying Lee, about it being sad that you can’t rely on this code to be maintained and that it feels like Google discontinuing a product. 
The situation is that we are a small team that makes internal tools for Google, not supported products for public use. The disclaimer in the README was insufficient in communicating this and we want to be clearer about what people should expect from this project in github going forward. This is why I thought this post should not promise updates but still encourage people to learn from our approach to malware protection at our scale.
There is a small chance that we will be able to make another release but it is unlikely that it will be soon and it is very unlikely that it will be with ongoing support.

**Comment by leereichardt** [comment]
Thanks @bengrooters, appreciate the reply!
